# Current jekyll theme
theme: jekyll-theme-architect

# Website name
name: Eduardo Messias

# Website title
title: Eduardo Messias

# Root directory
baseurl: ""

# Website root url
url: https://eduardomessias.github.io
