# Current jekyll theme
theme: jekyll-theme-leap-day

# Website name
name: Eduardo Messias

# Website title
title: Eduardo Messias

# Root website directory
baseurl: ""

# Website root url
url: https://eduardomessias.github.io

# Jekyll markdown capabilities extension
markdown: kramdown
